### ISSUE TITLE
[Bug] macos第一次使用，一直提示加载数据库失败，请重置数据库

### ISSUE THREAD

**Issue by SagittariusVampire** [BTMuli/TeyvatGuide#131]
### Issue Check

- [x] 我确认查找过相关的 Issue
- [X] 我确认这个问题是影响使用的
- [X] 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)

### 问题描述

<img width="240" alt="image" src="https://github.com/user-attachments/assets/a189b52c-ba5d-414e-a937-3f58f25d2f7e">

<macos15.0.1>  一直提示这个，我把数据库文件删除，再次点击设置，还是相同问题。
日志信息：
[2024-10-21][09:57:37][ERROR][Q@tauri://localhost/assets/@tauri-apps-CodgtwTI.js:1:26606] 加载数据库错误: error returned from database: (code: 1) no such table: AppData
日志信息中的时间也不对，实际时间是2024年10月21日17:57:37，时区不对。相差8小时

### 当前使用版本

v0.6.0-beta

### 复现流程

打开软件，点击设置，就会出现

**Comment by BTMuli** [comment]
已知bug，设置页点击更新数据库即可

**Comment by BTMuli** [comment]
最新版本已经修复改bug
