### ISSUE TITLE
[Bug] 一直提示“请先登录”

### ISSUE THREAD

**Issue by CRoyL** [BTMuli/TeyvatGuide#132]
### Issue Check

- [X] 我确认查找过相关的 Issue
- [X] 我确认这个问题是影响使用的
- [X] 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)

### 问题描述

在设置界面登录后，左边选项卡“原神战绩”、“我的角色”、“深渊记录”、“祈愿记录”都没问题，能查到我的信息。
但“帖子”里的二级选项和左下角个人信息点进去的“签到”、“战绩”会提醒我先登录。

### 当前使用版本

0.6.1 Beta

### 复现流程

卸载重装，仍一样的问题。

**Comment by BTMuli** [comment]
已知bug，这几天会发新版本修复该问题

**Comment by BTMuli** [comment]
https://github.com/BTMuli/TeyvatGuide/commit/670146400211751128e0551a7e82167f3b379baf
