### ISSUE TITLE
[Bug] 使用网页登陆后依然是未登陆状态

### ISSUE THREAD

**Issue by cntvc** [BTMuli/TeyvatGuide#99]
### Issue Check

- [X] 我确认查找过相关的 Issue
- [X] 我确认这个问题是影响使用的
- [X] 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)

### 问题描述

使用网页登陆后，点击“用户登陆”按钮，提示登陆成功，但依然是未登陆状态，无法使用便签等功能。
点刷新状态也没用。

### 当前使用版本

v0.4.3.dev

### 复现流程

依次点击按钮：
1. 网页登陆
2. 安全退出
3. 短信登陆
4. 用户登陆

**Comment by BTMuli** [comment]
![0C8ED239E46E039FBBF9685D70C9DBE2](https://github.com/BTMuli/TeyvatGuide/assets/72692909/f52d3fea-6cf8-4766-8263-306dfbcf4abc)

**Comment by cntvc** [comment]
> ![0C8ED239E46E039FBBF9685D70C9DBE2](https://private-user-images.githubusercontent.com/72692909/312049604-f52d3fea-6cf8-4766-8263-306dfbcf4abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDE5NjksIm5iZiI6MTcxMDI0MTY2OSwicGF0aCI6Ii83MjY5MjkwOS8zMTIwNDk2MDQtZjUyZDNmZWEtNmNmOC00NzY2LTgyNjMtMzA2ZGZiY2Y0YWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTc4NmM4MDk1ZTQxODlmMjNlMzljYWI3NGQxMGZmMjNjYTE3NTg5YTdlZmMzMDk2OWMzNjk5M2NmYTgyYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnUgurEWCHzO4_wsXp_5gWMXP0wz7b-dU9LGNmHWIF8)

是这样操作的，登陆状态没有刷新，必须点击旁边刷新按钮后左侧导航栏才显示出昵称，
但是设置页面的需要重新进入才会显示出昵称

> ![0C8ED239E46E039FBBF9685D70C9DBE2](https://private-user-images.githubusercontent.com/72692909/312049604-f52d3fea-6cf8-4766-8263-306dfbcf4abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDMwMzksIm5iZiI6MTcxMDI0MjczOSwicGF0aCI6Ii83MjY5MjkwOS8zMTIwNDk2MDQtZjUyZDNmZWEtNmNmOC00NzY2LTgyNjMtMzA2ZGZiY2Y0YWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOTZiOWViMTIzMWQ2OWViY2IzMzEwYmVmNmZhOTAwNmRhNTIwODlhYTZiYmI4YzBlOTcwMWEzOWZmNmIxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AAoQ-V8_R2zoefBIJbuw39Do-d6ya2pfdM0BCpLmnIg)

是这样操作的，没有漏掉第4步。
点了之后并没有成功登陆，必须点击旁边刷新按钮后才可以（~~之前好像点刷新按钮也不行~~
另外在点了刷新按钮后后设置页面的用户登陆Panel没有更新，需要重新进入才会显示出昵称。

![动画](https://github.com/BTMuli/TeyvatGuide/assets/119989194/6c231f37-b7de-4819-b1b6-21496ac5b1a9)

**Comment by BTMuli** [comment]
> 是这样操作的，登陆状态没有刷新，必须点击旁边刷新按钮后左侧导航栏才显示出昵称， 但是设置页面的需要重新进入才会显示出昵称

> 是这样操作的，没有漏掉第4步。 点了之后并没有成功登陆，必须点击旁边刷新按钮后才可以（~之前好像点刷新按钮也不行~ 另外在点了刷新按钮后后设置页面的用户登陆Panel没有更新，需要重新进入才会显示出昵称。

~~前面俩图裂了，建议发群里~~，最后一个 gif 酒馆没有登录是正常的，因为这部分我没有写相关处理

左侧导航栏信息跟设置页用户信息是数据响应式的问题，实际上数据库里已经有了用户数据

~~还是建议群里讨论，测试也好测~~
